# Generated by Django 5.2.6 on 2025-11-09 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=200, unique=True)),
                ('prefix', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CompServices',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('mac_address', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_id', models.IntegerField()),
                ('service_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
            options={
                'unique_together': {('department', 'service_id')},
            },
        ),
    ]
