<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-11-03 05:19

=======
>>>>>>> f7ab577c541ae732dae46b59b650735189afc0be
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=200, unique=True)),
                ('prefix', models.CharField(max_length=10)),
            ],
        ),
    ]
