# Generated by Django 5.2.6 on 2025-11-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='username',
        ),
        migrations.AddField(
            model_name='counter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
