# Generated by Django 5.2.5 on 2025-11-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_counter_email'),
        ('counter', '0002_remove_counter_username_counter_email'),
    ]

    operations = [
    ]
