<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-11-03 05:19
=======
# Generated by Django 5.2.5 on 2025-11-14 05:12
>>>>>>> counter

=======
>>>>>>> f7ab577c541ae732dae46b59b650735189afc0be
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=20)),
                ('lane', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Called', 'Called'), ('Served', 'Served'), ('Skipped', 'Skipped'), ('Cancelled', 'Cancelled')], default='Waiting', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('queue_position', models.IntegerField(default=0)),
<<<<<<< HEAD
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.compservices')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service')),
=======
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('assigned_counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='accounts.counter')),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.compservices')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.service')),
>>>>>>> counter
            ],
            options={
                'unique_together': {('service', 'ticket_number', 'issued_date')},
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=20)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
        ),
    ]
