<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-10-27 12:22
=======
# Generated by Django 5.2.7 on 2025-10-09 07:17
>>>>>>> createticket

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='service',
<<<<<<< HEAD
            field=models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='services.service'),
=======
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
>>>>>>> createticket
        ),
    ]
