# Generated by Django 5.2.6 on 2025-10-02 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='log',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='Counter',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
