# Generated by Django 5.2.7 on 2025-10-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='priority',
            new_name='lane',
        ),
    ]
