# Generated by Django 5.2.7 on 2025-10-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_rename_priority_ticket_lane'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='queue_position',
            field=models.IntegerField(default=0),
        ),
    ]
