<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-11-04 06:10
=======
<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-11-03 10:19
=======
# Generated by Django 5.2.6 on 2025-11-03 05:19
>>>>>>> 0a5245878b808ccb6032124d822e063bfa7ae5a0
>>>>>>> 8ec6579a647d792290a6635a007df74e7f587252

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompServices',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=50, unique=True)),
                ('mac_address', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_id', models.IntegerField()),
                ('service_name', models.CharField(max_length=100)),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service', to='services.compservices')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
            options={
                'unique_together': {('department', 'service_id')},
            },
        ),
    ]
