# Generated by Django 5.2.6 on 2025-11-06 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompServices',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('mac_address', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_id', models.IntegerField()),
                ('service_name', models.CharField(max_length=100)),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service', to='services.compservices')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
            options={
                'unique_together': {('department', 'service_id')},
            },
        ),
    ]
