# Generated by Django 5.2.6 on 2025-11-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='comp',
        ),
    ]
